TS 24: Рисуем лендинг на тематику ВКР
karauul/tourfirm pull request #2
Opened 2023-01-08 16:44 UTC by karauul

2023-01-12 17:41 UTC, SleptsovBoris commented on src/components/Cart/Components/CartItemsTab/CartItemsTab.tsx
> +import ButtonGroup from 'antd/es/button/button-group';
Убрать неиспользуемый импорт

2023-01-12 17:45 UTC, SleptsovBoris commented on src/components/NavBar/NavBar.tsx
> +    const rootNode = document.getElementById('root'[0]);
Убрать неиспользуемый rootNode

2023-01-14 20:32 UTC, VladislavAripov requested changes

2023-01-14 20:32 UTC, VladislavAripov commented on src/App.tsx
> +  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Ve
Переименуй константу в aboutText и напиши пару строк о своей компании вместо "Lorem ipsum.."

2023-01-14 20:32 UTC, VladislavAripov commented on src/App.tsx
> +  };
Ошибка в именовании
Нужно: handleRemoveItemFromToCart -> handleRemoveItemFromCart

2023-01-14 20:32 UTC, VladislavAripov commented on src/App.tsx
> +        </div>
Заполни about-area инфой по своей компании

2023-01-14 20:32 UTC, VladislavAripov commented on src/components/Cart/Cart.tsx
> +export default Cart;
Добавь пустую строку между компонентом и export default.. и в конце файла должна быть пустая строка. Посмотри по всем файлам. Между любыми объектами (компонент, интерфейс, функция, экспорт, после импортов)

2023-01-14 20:32 UTC, VladislavAripov commented on src/components/Cart/Components/CartItemsTab/CartItemsTab.tsx
> +  const handleAddOrder = () => {
Добавь отступ перед функцией

2023-01-14 20:32 UTC, VladislavAripov commented on src/components/Cart/Components/CartItemsTab/CartItemsTab.tsx
> +              <Button
Лишний отступ

2023-01-14 20:32 UTC, VladislavAripov commented on src/components/Cart/Components/CartItemsTab/CartItemsTab.tsx
> +export default CartItemsTab;
Отступы

2023-01-14 20:32 UTC, VladislavAripov commented on src/components/NavBar/NavBar.tsx
> +export default NavBar;
Отступ

2023-01-14 20:32 UTC, VladislavAripov commented on src/components/Products/Products.tsx
> +    },
Заполни туры инфой - заголовки и описание. Чтобы карточки между собой различались

2023-01-14 20:32 UTC, VladislavAripov commented on src/components/Products/Products.tsx
> +  return (
Отступ

2023-01-14 20:32 UTC, VladislavAripov commented on src/components/Products/Products.tsx
> +export default Products;
Отступ

2023-01-14 20:32 UTC, VladislavAripov commented on src/components/Products/components/Product/Product.tsx
> +  return (
Отступ

2023-01-14 20:32 UTC, VladislavAripov commented on src/components/Products/components/Product/Product.tsx
> +export default Product;
Отступ

2023-01-14 20:32 UTC, VladislavAripov commented on src/constants/cookiesNames.ts
> +export default cookiesNames;
Отступ

2023-01-14 20:35 UTC, VladislavAripov commented
Выбери нужное между about.png и about2.png и удаление лишнее

2023-01-14 20:56 UTC, VladislavAripov requested changes

2023-01-14 20:56 UTC, VladislavAripov commented on src/App.css
>  }
Раздели визуально стили как сделал Борис. Это комментарий ко всем .css файлам

2023-01-14 20:56 UTC, VladislavAripov commented on src/App.tsx
> +    </>
Раздели блоки header, body, footer как сделал Борис

2023-02-05 11:31 UTC, VladislavAripov approved these changes

2023-02-05 11:33 UTC, merged